### ISSUE TITLE
Unable to zoom up the image

### ISSUE THREAD

**Issue by VittorioAccomazzi** [VittorioAccomazzi/LeafSize#12]
With the latest version of Chrome (107.0.5304.87) as soon as I attempt to zoom up the image I receive an error. The error stack is the following:
```
Encounterd Error Failed to execute 'matrixTransform' on 'DOMPointReadOnly': The is2D member is set to true but the input matrix is a 3d matrix..

Stack: 
TypeError: Failed to execute 'matrixTransform' on 'DOMPointReadOnly': The is2D member is set to true but the input matrix is a 3d matrix.
     at displayCanvas (http://localhost:3000/LeafSize/static/js/bundle.js:6652:19)
     at AutoZoom (http://localhost:3000/LeafSize/static/js/bundle.js:6626:7)
     at renderWithHooks (http://localhost:3000/LeafSize/static/js/bundle.js:64935:22)
     at updateFunctionComponent (http://localhost:3000/LeafSize/static/js/bundle.js:69007:24)
     at beginWork (http://localhost:3000/LeafSize/static/js/bundle.js:70983:20)
     at beginWork$1 (http://localhost:3000/LeafSize/static/js/bundle.js:75786:18)
     at performUnitOfWork (http://localhost:3000/LeafSize/static/js/bundle.js:74984:16)
     at workLoopSync (http://localhost:3000/LeafSize/static/js/bundle.js:74898:9)
     at renderRootSync (http://localhost:3000/LeafSize/static/js/bundle.js:74867:11)
     at performSyncWorkOnRoot (http://localhost:3000/LeafSize/static/js/bundle.js:74511:24)NaN
```

**Comment by VittorioAccomazzi** [comment]
An example of matrix causing the problem is the following:
<img width="1114" alt="Screen Shot 2022-11-06 at 9 21 52 PM" src="https://user-images.githubusercontent.com/7923323/200213465-8f883366-09bf-4f36-b4c4-9472a04f228e.png">

Based on the [chromium code](https://chromium.googlesource.com/chromium/src/+/ceec5078d982398f334025bb4c2bb5c01d39d42c/third_party/WebKit/Source/core/geometry/DOMMatrixReadOnly.cpp), I see that the test made is for `m33` and `m44` to be exactly 1.0. Since they are floating point I believe they should add some tolerance, anyway, the matrix above doesn't have the value 1 because result of an inversion.

**Comment by VittorioAccomazzi** [comment]
The problem is fixed.
